### ISSUE TITLE
Error while setting up anniversaries platform for sensor

### ISSUE THREAD

**Issue by floodwayprintco** [pinkywafer/Anniversaries#105]
I'm having trouble with this integration, but I've had it working fine before. I'm not totally sure what the issue is based on this error.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/anniversaries/sensor.py", line 39, in async_setup_platform
    async_add_entities([anniversaries(hass, discovery_info)], True)
  File "/config/custom_components/anniversaries/sensor.py", line 59, in __init__
    self._name = config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'`

Here is my config, edited a bit for privacy.

```
############################
### Birthday Countdowns
 - platform: anniversaries
   name: Birthday Floodway
   date: '2014-07-01'
   icon_normal: mdi:cake-variant

 - platform: anniversaries
   name: Birthday Me
   date: '1999-05-25'
   icon_normal: mdi:cake-variant   
   
 - platform: anniversaries
   name: Birthday John
   date: '1999-05-25'
   icon_normal: mdi:cake-variant    
   
 - platform: anniversaries
   name: Birthday Jane
   date: '1999-05-25'
   icon_normal: mdi:cake-variant 
```

**Comment by pinkywafer** [comment]
I can't see the top level key in your config, but I believe you're trying to setup under the `sensors:` heading.
The configuration changed (I can't remember how long ago, but it was when I added support for using the integrations page).
You can either simply delete your configuration.yaml entries and use the UI on the integrations page, or use the newer configuration:
your entries would be under the `anniversaries:` key as follows:

``` yaml
############################
### Birthday Countdowns
anniversaries:
  sensors:
    - platform: anniversaries
       name: Birthday Floodway
       date: '2014-07-01'
       icon_normal: mdi:cake-variant

    - platform: anniversaries
       name: Birthday Me
       date: '1999-05-25'
       icon_normal: mdi:cake-variant   
   
    - platform: anniversaries
       name: Birthday John
       date: '1999-05-25'
       icon_normal: mdi:cake-variant    
   
    - platform: anniversaries
       name: Birthday Jane
       date: '1999-05-25'
       icon_normal: mdi:cake-variant 
```

**Comment by pinkywafer** [comment]
just realised I posted this wrongly! - it should be:
```yaml
############################
### Birthday Countdowns
anniversaries:
  sensors:
     - name: Birthday Floodway
      date: '2014-07-01'
      icon_normal: mdi:cake-variant

    - name: Birthday Me
      date: '1999-05-25'
      icon_normal: mdi:cake-variant   
   
    - name: Birthday John
      date: '1999-05-25'
      icon_normal: mdi:cake-variant    
   
    - name: Birthday Jane
      date: '1999-05-25'
      icon_normal: mdi:cake-variant 
```
