### ISSUE TITLE
Only displaying the remaining days by number

### ISSUE THREAD

**Issue by DrSpaldo** [pinkywafer/Anniversaries#121]
Currently for today & tomorrow it reports today or tomorrow. Is there a way you can set it to just say 0 or 1? 

The today and tomorrow aren't working for when I put the anniversaries entry into the auto-entities card. It skips anything that is today or tomorrow but works on anything that has the number x days

**Comment by DrSpaldo** [comment]
I ended up creating a template sensor as follows:

```
  - platform: template
    sensors:  
      bin_recycling:
        friendly_name: 'Recycling Bin Days'
        unit_of_measurement: 'Days'
        value_template: >
          {% set days = states('sensor.recycling') %}
          {{ {'today': 0, 'tomorrow': 1}.get(days, days) }}
```
