### ISSUE TITLE
Using date_template

### ISSUE THREAD

**Issue by tdvantine** [pinkywafer/Anniversaries#126]
I went through the other issues that mention date_template, but none of them have an example of how to use the YAML. Currently I have: 
```
anniversaries:
  sensors:
  - name: D34B
    date_template: {{ states('input_datetime.tristan_visit') }}
```

But I am getting the error:
```
Error loading /home/homeassistant/.homeassistant/configuration.yaml: invalid key: "OrderedDict([("states('input_datetime.tristan_visit')", None)])"
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 93, column 0
```

**Comment by tdvantine** [comment]
I am oblivious and forgot to add the single/double quotes to the single line template. 
Anyone that comes across this in the future this is what is should look like:
 ```
anniversaries:
  sensors:
  - name: tristan_visit
    date_template: "{{ states('input_datetime.tristan_visit') }}"
```
