### ISSUE TITLE
Feature request or a way to categorize items

### ISSUE THREAD

**Issue by arnolddej** [pinkywafer/Anniversaries#141]
# **Feature request, NOT a bug**

Good day,

Just found out this integration. Looks very useful!

However, I would like to categorize the basic stuff, for example birthdays, weddings/jubilee, regular car checks, tax etc.
So in the case of birthdays, you do not have to write: _xname_'s **Birthday** over and over again.

```yaml
anniversaries:
  sensors:
 -  type: birthday: #something like this maybe?
   - name: Arnold's Birthday
     date: '1900-01-01'
   - name: Henk's Birthday
     date: '1900-01-01'
   - name: Joep's Birthday
     date: '1900-01-01'
 - type: jubilee (wedding date) #something like this maybe?
   - name: Henk & Ingrid 
     date: '2020-12-12'
 - type: uncategorized:
   - name: Car inspection
     date: '11-29'
```

Maybe is the idea above something or is there already something possible like this?
Or is it just me who wants to have clean consistent yaml files 😬
