### ISSUE TITLE
Future request: to show how old person is.

### ISSUE THREAD

**Issue by tevas007** [pinkywafer/Anniversaries#152]
Just future request,, if possible: an option to show how old person is, if date format YYYY-MM-DD is used.

**Comment by JeffCrum1** [comment]
No idea what this 'feature request' is since there is already an attribute, current_years, that has that information.

What am I missing?

In Developer Tools | Template, put:
```
{{ state_attr('sensor.anniversary_jeff_bday', 'current_years') }}
```

**Comment by tevas007** [comment]
Hello,
ok... thank you. now i am able to get/show that info in template result,
but how to add that information to the dashboard ?

Ramunas

**Comment by tevas007** [comment]
Ok, i have figured out. Thank you1

**Comment by bt-beardedtechie** [comment]
Hi can you tell me how you accomplished this in UI? I'm unable to show in my calendar or in my atomic calendar card on my dashboard.

**Comment by BebeMischa** [comment]
using two HACS delivered cards - auto-entities and multiple-entity-row

```
type: custom:auto-entities
card:
  show_name: true
  show_icon: true
  show_state: true
  type: entities
  state_color: true
  columns: 3
  title: Verjaardagen
filter:
  include:
    - entity_id: sensor.anniversary*
      options:
        type: custom:multiple-entity-row
        entity: this.entity_id
        entities:
          - attribute: years_at_anniversary
            unit: jaar over
  exclude:
    - entity_id: sensor.anniversary_concert*
sort:
  method: state
  numeric: true
```

I get this:

![image](https://github.com/user-attachments/assets/8b118716-7685-438d-a0c9-304fb280257a)


Of course you can ignore the exclude, I'm using anniversaries also for countdowns on my concerts visits :-)

**Comment by bt-beardedtechie** [comment]
I'll check this out. 

I am trying to add this to my atomic calendar card. Would the same steps work for that as well?

**Comment by JeffCrum1** [comment]
I have no idea about the atomic calendar card.  But, similar to @BebeMischa I do get these into a list in a card.

But I use a custom flex-table-card like this:

I name my anniversaries entries as ...
[name] BDay
So, I remove BDay from the output as you can see in the Name column using the modify.

```
type: custom:flex-table-card
title: Birthdays
entities:
  include: sensor.anniversary_*bday
sort_by: friendly_name+
css:
  tbody tr+: "user-select: text"
columns:
  - name: Name
    data: friendly_name
    modify: x.replace(' BDay', '')
  - name: Birthdate
    data: date
    modify: >-
      var date = new Date(x); const months = ['January ','February ','March
      ','April ','May ','June ','July ','August ','September ','October
      ','November ','December ']; months[date.getMonth()] +
      String(date.getDate())
  - name: Age
    data: current_years
    align: right
  - name: Days
    data: state
    align: right
```
And it looks like
![image](https://github.com/user-attachments/assets/17efa380-f385-4a06-9ded-b7113adb7747)
