### ISSUE TITLE
Show only a couple days before a date

### ISSUE THREAD

**Issue by dannymertens** [pinkywafer/Anniversaries#37]
Hi,

Is it possible to show entries only before a certain date, so birthdays 5 days before or something like that?

**Comment by pinkywafer** [comment]
The entity will always be available to home assistant,  but you could filter entities to display using an entity-filter card, for example: 
```yaml
type: entity-filter
card:
  type: entities
entities:
  - sensor.jenny_s_birthday
state_filter:
  - operator: <
    value: 100
```
