### ISSUE TITLE
Non-recurring dates

### ISSUE THREAD

**Issue by LazyTarget** [pinkywafer/Anniversaries#38]
Hi! Really like this integration as it gives an simple and easy "calendar" in my lovelace views.

I have one feature request, that is to be able to set _non-recurring anniversaries_.

Example:
I have anniversaries for Christmas and New Year. These always occur on the 24 or 25 (depending on the country) and New Year is always on December 31st. So this integration works great for these holidays (except that i don't care the year of this "anniversary")

But I would also like to add some other, _"relative"_ holidays, those that can move a few days every year. 
For example: Easter or the Swedish Midsummer holiday

One way would be to have a property called "absolute" that when set to "true" 
=> Makes the anniversary only occur once.

**Comment by pinkywafer** [comment]
I don't see any reason why I couldn't include a 'non-recurring' option for an anniversary, but I'm not certain that it would be of any use, unless you wanted to know how long since an event occured or until a one-off date.
I'm going to leave this open as a feature request for now to gauge how useful it would be.
However, for things which do recur, but on other dates (ie. easter) you could try my calendarific sensor or a similar thing from someone else (I use calendarific as my holiday date source, so it's set once and forget!)

**Comment by LazyTarget** [comment]
Yes, I wanted it for a one-off date. But I  realize that it would leave a bunch of old sensors that don't have any purpose after they have occured. Which is a complete waste..

Didn't even think of a feature such as "how long since an event occured". Maybe someone wants such a feature, we can wait and see like you say. Currently I don't have a need for that. 

Great! I completly missed it, will check out calendarific :smile:

Thanks!

**Comment by twochannel** [comment]
Days-since would be nice.  I was starting to looking into a days-since-we-all-were-told-to-stay-home but gave up when I thought I wanted week-days only to track since the kids were in school or me at work. I didn't have the time for that rabbit hole. 

For one-offs or non-yearly I use the google calendar integration. I create a template sensor off the event sensor that calculates proper days until the day of the event (instead of the accounting for the time of the event) as the entity state. This would also lets me add other template driven attributes such as weekday, etc.

There is likely a simpler way than the jinja2/timestamp gymnastics I'm performing, but it works!

```yaml
  - platform: template
    sensors:
      calendar_me_gmail_com:
        friendly_name: "Gmail Calendar events"
        value_template: >
                        {%- set event_date = as_timestamp(as_timestamp(states.calendar.me_gmail_com.attributes.start_time) | timestamp_custom('%Y-%m-%d') ~ " 00:00")  -%}
                         {%- set now_date = as_timestamp(as_timestamp(now()) | timestamp_custom('%Y-%m-%d') ~ " 00:00") -%}
                         {{((event_date - now_date)/86400) | int }} days
        attribute_templates:
          weekday: "{{ as_timestamp(states.calendar.me_gmail_com.attributes.start_time) | timestamp_custom('%c')}}"
```

For types of events I just add or create those calenders in my google account.  US holidays, sports team schedule, work holidays, family birthdays, personal appointments, big events like vacations, etc.  I end up with about 7 sensors all counting down to the next event for that calendar (or integration search term).  One thing I've yet to solve is two events on the same day. I expect that to be an issue given how the google calendar integration works.  It's on the to-do list for now.

I use anniversaries for very important dates I always want to see (anniversary, immediate family birthdays)  

..and not to ramble, but as I was writing this I realized my sports team calendar updates the event title to include the score of the game once its over.  I wish the google calendar integration was more flexible for what dates it pulled
