### ISSUE TITLE
Add custom entity_id prefix

### ISSUE THREAD

**Issue by LazyTarget** [pinkywafer/Anniversaries#39]
It would be great to have a property next to the date, that could specify a custom label. Instead of using the entity id.

I currently have a this setup:

**/configuration.yaml**
```
homeassistant:
  customize: !include_dir_merge_named "yaml/customizations/"

anniversaries: !include "yaml/root/anniversaries.yaml"
```

**/yaml/root/anniversaries.yaml**
```
sensors:
  - name: "anniversary_event_first_may"
    date: '2000-05-01'
  - name: "anniversary_may_the_forth"
    date: '1977-05-04'
  - name: "anniversary_event_christmas"
    date: '2000-12-24'
  - name: "anniversary_event_newyear"
    date: '1999-12-31'
```

**/yaml/customizations/anniversaries.yaml**
```
sensor.anniversary_event_first_may:
  friendly_name: Första maj
sensor.anniversary_may_the_forth:
  friendly_name: May the 4th be with you
sensor.anniversary_event_christmas:
  friendly_name: Jul
sensor.anniversary_event_newyear:
  friendly_name: Nyår
```

I would not be needing the customizations file, if only I could set a label directly on the sensor.
It would help a lot but not having to make sure that the files are in sync, whenever I add a new anniversary.
Is this possible to implement?
