### ISSUE TITLE
Companion lovelace card

### ISSUE THREAD

**Issue by mgriffin13** [pinkywafer/Anniversaries#7]
I've been looking for ways to display my list of anniversaries in lovelace, and I came across https://github.com/erlsta/homeassistant-lovelace-birthday-reminder-card, which gives what I'm looking for in terms of lovelace displays. The issue is that card hard-codes all the data into the javascript and I would prefer to use this plugin's sensors as the data source, so that I only have to define the anniversary dates once, but I could use them in both lovelace displays and automations.

My vision would be a Lovelace card that can be defined like the following and it would generate a Lovelace card like the screenshot in that repo.

```
type: "custom:anniversaries"
title: "Important Dates"
numberofdays: 30
entities:
  - sensor.gladys_birthday
  - sensor.grandfather_passing
  - sensor.adam_birthday
  - sensor.amanda_birthday
  - sensor.wedding_anniversary
  - sensor.peter_birthday
```

**Comment by pinkywafer** [comment]
I hadn't thought of adding it's own custom card, but it does look neat like that, so I'll see what I can do. All the information needed is there in the sensor, so shouldn't be too difficult!

**Comment by mgriffin13** [comment]
I've also been playing with a combination of other custom cards, specifically `secondaryinfo-entity-row` (not in HACS) and `vertical-stack-in-card` (in HACS), which actually might look a little better, but doesn't provide the features like auto-hide if not "soon", auto sort, colored icons, etc. Plus, the card definition is getting pretty heavy with all the custom cards, so having a single custom card would definitely simplify everything.

Here's my sample grouping that I've got so far.

```
cards:
  - entities:
      - entity: sensor.mike_birthday
        secondary_info: >-
          [[ {entity}.attributes.date ]]  ( [[
          {entity}.attributes.years_at_next_anniversary ]] Years )
        type: 'custom:secondaryinfo-entity-row'
      - type: divider
      - entity: sensor.jenn_birthday
        secondary_info: >-
          [[ {entity}.attributes.date ]]  ( [[
          {entity}.attributes.years_at_next_anniversary ]] Years )
        type: 'custom:secondaryinfo-entity-row'
      - type: divider
      - entity: sensor.wedding_anniversary
        secondary_info: >-
          [[ {entity}.attributes.date ]]  ( [[
          {entity}.attributes.years_at_next_anniversary ]] Years )
        type: 'custom:secondaryinfo-entity-row'
    type: entities
title: Our Events
type: 'custom:vertical-stack-in-card'
```

![events](https://user-images.githubusercontent.com/5270404/69112492-5ea7bf00-0a4e-11ea-8386-81823a0dd312.png)

**Comment by pinkywafer** [comment]
FYI: Secondaryinfo Entity Row is now on HACS,
it should be possible to filter any events which are not 'soon' (or any other time period) using an entity filter card instead, or it might be possible to both sort and filter using thomaslovens' lovelace-auto-entities card, but I can definitely see the config for any of these getting rather over complicated!

**Comment by mgriffin13** [comment]
Playing around some more, the lovelace-auto-entries card wasn't as bad as I thought. I just need to make sure to create the entity as `sensor.dates_<name>` so that I can easily filter.

```
card:
  show_header_toggle: false
  title: Important Dates
  type: entities
sort:
  method: state
  numeric: true
filter:
  include:
    - entity_id: /dates/
      state: < 120
      options:
        type: 'custom:secondaryinfo-entity-row'
        secondary_info: >-
          [[ {entity}.attributes.date ]]  ( [[
          {entity}.attributes.years_at_next_anniversary ]] Years )
show_empty: true
type: 'custom:auto-entities'
```

**Comment by pinkywafer** [comment]
That looks quite neat and wouldn't require changing for extra entities.

**Comment by brianhanifin** [comment]
Here is my version. Since I do not include `dates` in the sensor name, I created an `or` list which includes entity_ids with `anniversary` or `birthday` or `wedding` and does not include entity_ids with `automation.` or `calendar.` or `scene.` or `script.`.
```yaml
- type: custom:auto-entities
  show_empty: true
  card:
    show_header_toggle: false
    title: Important Dates
    type: entities
  sort:
    method: state
    numeric: true
  filter:
    include:
      - entity_id: /anniversary|birthday|wedding/
        #state: < 120
        options:
          type: custom:secondaryinfo-entity-row
          secondary_info: >-
            [[ {entity}.attributes.date ]]  ( [[
            {entity}.attributes.years_at_next_anniversary ]] Years )
    exclude:
      - entity_id: /automation.|calendar.|scene.|script./
```
