### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by fredrikbaberg** [pinkywafer/Anniversaries#8]
The readme seem to have invalid config with the new breaking change, since the example does not work.
The issue seem to be resolved through removing `platform: anniversaries`, which is no longer needed with the new setup.

```
anniversaries:
  sensors:
  - name: Shakespeare's Birthday
    date: '1564-04-23'
  - name: Shakespeare's Wedding Anniversary
    date: '1582-11-27'
```
