### ISSUE TITLE
Count Up

### ISSUE THREAD

**Issue by julianrinaldi** [pinkywafer/Anniversaries#84]
I would love if we could set the option to set the entity to count up from a date instead of counting down to the date. So instead of it being "287 Days" until an anniversary, we can show it as "77 Days" since an anniversary.

**Comment by pinkywafer** [comment]
this ought to be possible

**Comment by MrDrache333** [comment]
Same for me. I would love to see this feature. Maybe as a simple Option as a CheckBox 😃
Maybe even automatically? If its a one Time event and the Day is over...its one Day since....
This was even my logic when I tried this out. But instead, if I type for example 2020-05-24 in, the sensor would give me 486...and that's....? Whatever this is...Its 365 + the Days left to the next occurrency...but why?

**Comment by MrDrache333** [comment]
Ive added the Feature in my [Pull-Request](https://github.com/pinkywafer/Anniversaries/pull/88#issue-560481581)

**Comment by pinkywafer** [comment]
One time events should not count to the next anniversary, as they are "one-time"  This was a bug which should be resolved by #90 
After the date, the days should be -1, -2, -3 etc
I'm leaving this issue open though as I don't think it's addressed by this PR.

My take on the issue is:
* Allow choice
  * count down (default) - as now with fixed one time events
  * count up - negative numbers before the date, positive after
  * count in both directions - count down to the date, then count up again one off for a one-time event, until / after within the year for recurring dates

Any thoughts on this interpretation?

**Comment by jobvk** [comment]
I have made a easy solution until this option is available in the integration itself.

```
Sensor:
  - platform: template
    sensors:
      custom_date:
        friendly_name: "Days since input custom date"
        value_template: "{{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.custom_date'))) / 86400) | int }}"
        icon_template: mdi:calendar-blank
        unit_of_measurement: "Days"
```

With **input_datetime** you can select a date and time and use it for a timestamp
```
input_datetime:
  custom_date:
    name: Custom Date
    has_date: true
    has_time: true
```

Result:
![image](https://user-images.githubusercontent.com/32730202/108738325-c98a5480-7533-11eb-8ee2-18f5bf7e903f.png)
