### ISSUE TITLE
Anniversary automations

### ISSUE THREAD

**Issue by SamKr** [pinkywafer/Anniversaries#85]
Thanks for the integration! 

Is there a way to use all anniversaries in one automation, instead of making one for every single one? Ie. send a message if any of the dates triggers tomorrow?

**Comment by pinkywafer** [comment]
At the moment, the easiest method would be to use something like:
```yaml
automation:
  - alias: New Automation
    trigger:
    - platform: state
      entity_id: 
        - sensor.anniversary_first_sensor
        - sensor.anniversary_second_sensor
        - sensor.anniversary_third_sensor
      to: '1'
    action:
      - service: persistent_notification.create
        data:
          message: '{{trigger.to_state.attributes.friendly_name}} is tomorrow!'
```
Just to run through this in the trigger we're checking for any of the entities listed changing to 1 (tomorrow)
Then in the action, we're creating a persistent notification with the information about which event is tomorrow.
`{{trigger.to_state.attributes.friendly_name}}` will return the friendly name of the entity that triggered the automation
ie.  if your sensor was set up with the name `Jenny's Birthday`, the persistent notification would have the message `Jenny's Birthday is tomorrow!`
You can use this for whatever you like, tts, mobile app notification etc, or you can trigger something altogether different.

**Comment by SamKr** [comment]
That is perfect! Thanks a lot for the extensive write up Jenny, and thanks again for sharing this project :)

**Comment by Metus88** [comment]
Sorry if I write inside an old closed issue... but I just copied the automation above, but it is triggered at midnight... there is a way to send the notification for example at 8:00 am? I don't like receiving a notification in the middle of the night... (telegram or tts)
Thanks for the help

**Comment by amibumping** [comment]
@pinkywafer sorry to open this conversation, but I have a doubt about this subject.

I am trying to make the notification in telegram, and when I put in the automation 
`service: notify.telegramamibumping
data:
  message: '{{trigger.to_state.attributes.friendly_name}} is tomorrow!'`
Appears this error:
`Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'to_state'`

How can I solve it?

**Comment by Metus88** [comment]
It's important that the trigger of automation is:
`  trigger:
  - platform: state
    entity_id:
    - sensor.anniversary_XXXXXX`

Are you sure to named the trigger correctly? (Are you sure the sensor.anniversary_XXXXXX exists? ). Can you share all the automation? Thanks

**Comment by Metus88** [comment]
> @pinkywafer sorry to open this conversation, but I have a doubt about this subject.
> 
> I am trying to make the notification in telegram, and when I put in the automation `service: notify.telegramamibumping data: message: '{{trigger.to_state.attributes.friendly_name}} is tomorrow!'` Appears this error: `Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'to_state'`
> 
> How can I solve it?

It's important that the trigger of automation is:
```
trigger:
  - platform: state
    entity_id:
    - sensor.anniversary_XXXXXX
 ```

Are you sure to named the trigger correctly? (Are you sure the sensor.anniversary_XXXXXX exists? ). Can you share all the automation? Thanks

**Comment by pinkywafer** [comment]
If the automation has been triggered by anything other than the state change of the anniversary sensor, then there will not be a to_state available

**Comment by amibumping** [comment]
`alias: Recuerdo cumpleaños
trigger:
  - platform: state
    entity_id: sensor.anniversary_cumpleanos_alberto
    to: '2'
action:
  - wait_template: '{{ states(''sensor.time'') == ''11:00'' }}'
  - service: notify.telegramamibumping
    data:
      message: '{{trigger.to_state.attributes.friendly_name}} is tomorrow!'
`

In the trigger I would like to put all the anniversaries that I've created in the config.yaml, not just one in order to avoid to create one automation for every anniversary

**Comment by pinkywafer** [comment]
You can put them all in the state trigger:
```yaml
- platform: state
  entity_id:
    - sensor.anniversary_first
    - sensor.anniversary_second
    # keep adding anniversary sensors here
to: '2'
```
